CREATE TABLE users(
    id BINARY(16) PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role ENUM('ADMIN', 'RUNNER', 'PREMIUM_RUNNER') DEFAULT 'RUNNER' NOT NULL
);


